# Generated by Django 4.2.20 on 2025-04-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('japanese', '国語'), ('math', '算数'), ('science', '理科'), ('social', '社会'), ('english', '英語'), ('other', 'その他')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('planned_date', models.DateField()),
                ('due_date', models.DateField()),
                ('estimated_minutes', models.PositiveIntegerField(default=30)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
