# Generated by Django 4.2.20 on 2025-04-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='due_date',
        ),
    ]
