# Generated by Django 4.2.20 on 2025-04-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_remove_homework_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('repeat', models.CharField(choices=[('none', '繰り返しなし'), ('weekly', '毎週'), ('monthly', '毎月')], default='none', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
