# Generated by Django 4.2.20 on 2025-04-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_remove_homework_estimated_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkdetail',
            name='scheduled_task',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
