# Generated by Django 4.2.20 on 2025-04-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_homeworkdetail_scheduled_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='planned_date',
        ),
    ]
