# Generated by Django 4.2.20 on 2025-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_remove_homework_planned_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('japanese', '国語'), ('math', '算数'), ('science', '理科'), ('social', '社会'), ('english', '英語'), ('other', 'その他')], max_length=20)),
                ('course', models.CharField(choices=[('master', 'マスターコース'), ('top_level', '最高レベル特訓')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
