# Generated by Django 4.2.20 on 2025-04-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkdetail',
            name='course',
            field=models.CharField(choices=[('master', 'マスターコース'), ('top_level', '最高レベル特訓'), ('second', '2nd')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lessontemplate',
            name='course',
            field=models.CharField(choices=[('master', 'マスターコース'), ('top_level', '最高レベル特訓'), ('second', '2nd')], max_length=20),
        ),
    ]
