# Generated by Django 4.2.20 on 2025-05-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0014_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.subject'),
        ),
        migrations.AlterField(
            model_name='lessontemplate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.course'),
        ),
    ]
