# Generated by Django 4.2.20 on 2025-05-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_alter_lesson_course_alter_lesson_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtemplate',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='repeat',
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='イベント'),
        ),
    ]
