# Generated by Django 4.2.20 on 2025-05-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0016_remove_eventtemplate_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='repeat',
        ),
    ]
