# Generated by Django 4.2.20 on 2025-05-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0018_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='イベントの名前'),
        ),
    ]
