# Generated by Django 4.2.20 on 2025-05-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0020_subjecttemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectTemplate',
        ),
    ]
