# Generated by Django 4.2.20 on 2025-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0021_delete_subjecttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
