# Generated by Django 4.2.20 on 2025-05-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0022_homeworksubjecttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='コース名')),
            ],
        ),
    ]
