# Generated by Django 4.2.20 on 2025-05-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0024_homeworkproblemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkProblemCountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='問題数')),
            ],
        ),
    ]
