# Generated by Django 4.2.20 on 2025-05-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0025_homeworkproblemcounttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkProblemCountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_count', models.PositiveIntegerField(verbose_name='最大問題数')),
            ],
        ),
        migrations.DeleteModel(
            name='HomeworkProblemCountTemplate',
        ),
    ]
